---
- name: Internal and external loadbalancer configuration
  hosts: loadbalancers
  become: yes
  roles:
    - role: loadbalancers
- name: Installing kubernetes node prequisite
  hosts: kubernetes_masters
  become: yes
  roles:
    - role: node-prepare
- name: initiating Kubernetes cluster with first master
  hosts: kubernetes_masters[0]
  become: yes
  roles:
    - role: cluster_initiator
