---
- name: Internal loadbalancer Keepalived configurations
  template:
    src: internal_lb_keepalived.j2
    dest: /etc/keepalived/keepalived.conf
    mode: 0644
  when: inventory_hostname in groups['internal_loadbalancers']
  tags: keepalived_config
  notify: Restart Keepalived
- name: External loadbalancer Keepalived configurations
  template:
    src: external_lb_keepalived.j2
    dest: /etc/keepalived/keepalived.conf
    mode: 0644
  when: inventory_hostname in groups['external_loadbalancers']
  tags: keepalived_config
  notify: Restart Keepalived
